spring.application.name=e-commerce

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/material
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=0000

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Server Port
server.port=8080
